# Generated by Django 6.0.3 on 2026-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('subject', models.CharField()),
                ('score', models.IntegerField()),
                ('grade', models.CharField()),
                ('pr_grade', models.CharField()),
            ],
        ),
    ]
